name: General Work Item
description: Create a structured request for a new feature, task, or data request
title: "[FEATURE]: "
labels: [feature]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Work Item Information
        Please complete all relevant fields to describe the purpose, scope, and expectations of this work item.

  - type: input
    id: product_manager
    attributes:
      label: Product Manager
      placeholder: "e.g., John Doe"

  - type: input
    id: developer
    attributes:
      label: Developer
      placeholder: "e.g., Jane Smith"

  - type: input
    id: code_reviewer
    attributes:
      label: Code Reviewer
      placeholder: "e.g., Alex Lee"

  - type: input
    id: priority
    attributes:
      label: Priority Group
      placeholder: "e.g., High / Medium / Low"

  - type: input
    id: strategic_objective
    attributes:
      label: Strategic Objective
      placeholder: "Describe the strategic alignment or objective"

  - type: input
    id: start_date
    attributes:
      label: Start Date
      placeholder: "YYYY-MM-DD"

  - type: input
    id: planned_completion
    attributes:
      label: Planned Completion Date
      placeholder: "YYYY-MM-DD"

  - type: input
    id: qa_date
    attributes:
      label: QA Date
      placeholder: "YYYY-MM-DD"

  - type: input
    id: original_release
    attributes:
      label: Original Release Date
      placeholder: "YYYY-MM-DD"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the work item.
      placeholder: |
        Include what needs to be built, extracted, or resolved.
        Include relevant context or technical background.

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        Define specific conditions that must be met for this item to be considered complete.

  - type: textarea
    id: desired_outcome
    attributes:
      label: Desired Outcome
      placeholder: |
        Summarize what success looks like and what the final deliverable should achieve.

  - type: input
    id: prospect_list
    attributes:
      label: Target or Prospect List
      placeholder: "e.g., Customer or Business Unit"

  - type: textarea
    id: business_success_plan
    attributes:
      label: Business Success Plan
      placeholder: |
        Explain how this work supports business goals, future use cases, or operational efficiency.

  - type: textarea
    id: tech_success_metrics
    attributes:
      label: Technical Success Metrics
      placeholder: |
        List the measurable technical outcomes for validation.

  - type: textarea
    id: impact_analysis
    attributes:
      label: Impact Analysis
      placeholder: |
        Describe the impact of this work on the platform, data, or business processes.

  - type: textarea
    id: security_requirements
    attributes:
      label: Security Requirements
      placeholder: |
        Indicate any data privacy, compliance, or legal requirements associated with this work.

  - type: textarea
    id: business_value
    attributes:
      label: Business Value
      placeholder: |
        Describe the estimated revenue, cost savings, customer benefit, or operational improvement.

  - type: input
    id: deployment_tracking
    attributes:
      label: Deployment Tracking Reference
      placeholder: "Link to release plan, dashboard, or deployment board"

  - type: textarea
    id: development_links
    attributes:
      label: Development Progress
      placeholder: "Link any related branches, PRs, or commits."

  - type: textarea
    id: related_work
    attributes:
      label: Related Work / Dependencies
      placeholder: "Mention parent/child issues, blockers, or dependencies."
