name: Format Issue as Comment

on:
  issues:
    types: [opened]

jobs:
  format_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Format and comment
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;

            // Helper to parse sections
            function getSection(label) {
              const regex = new RegExp(`\\*\\*${label}\\*\\*\\s*\\n(.*?)\\n(?=\\*\\*|$)`, 's');
              const match = body.match(regex);
              return match ? match[1].trim() : '_Not provided_';
            }

            const productManager = getSection("Product Manager");
            const developer = getSection("Developer");
            const summary = getSection("Work Summary");
            const criteria = getSection("Acceptance Criteria");

            const formatted = `
## 📝 Work Item Summary

**Product Manager:** ${productManager}  
**Developer:** ${developer}

---

## Description

${summary}

---

## Acceptance Criteria

${criteria}
`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: formatted
            });
